# ##############################################################################
# appveyor.yml
#
# Appveyor CI integration file
# 
# Copyright Chris Glover 2014-2015
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt
#
# ##############################################################################
environment:
  matrix:
    - GENERATOR: ""
      CONFIG: Debug

    - GENERATOR: ""
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release

build_script:
  - cmd: set BOOST_ROOT=c:\Libraries\boost
  - cmd: call C:\"Program Files (x86)"\"Microsoft Visual Studio 12.0"\VC\vcvarsall.bat
  - cmake "-GVisual Studio 12 %GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - if "x%GENERATOR%" == "x" ctest -VV -C "%CONFIG%"